# ────────────────────────────────────────────────────────────
# Omarchy Matte Black Theme for Alacritty (modified: red → dark purple)
# By tahayvr
# https://github.com/tahayvr
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 12
padding.y = 12

[font]
size = 12.0

[colors]
[colors.primary]
background = "#121212"
foreground = "#bebebe"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"

[colors.selection]
text = "CellForeground"
background = "#333333"

[colors.normal]
black = "#333333"
red = "#6A0DAD"
green = "#FFC107"
yellow = "#b91c1c"
blue = "#e68e0d"
magenta = "#6A0DAD"
cyan = "#bebebe"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#6A0DAD"
green = "#FFC107"
yellow = "#b90a0a"
blue = "#f59e0b"
magenta = "#6A0DAD"
cyan = "#eaeaea"
white = "#ffffff"
